truncate table customer restart identity cascade;
truncate table equipment_type restart identity cascade;
truncate table equipment restart identity cascade;
truncate table workshop restart identity cascade;
truncate table product restart identity cascade;        
truncate table task restart identity cascade;
truncate table planning restart identity cascade;
truncate table planning_process restart identity cascade;       
truncate table manufacturing_order restart identity cascade;